name: universal_tv
description: "Cross-platform IPTV application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  chopper: ^8.3.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  forui: ^0.19.0
  forui_assets: ^0.19.0
  go_router: ^17.0.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^2.0.1
  muxa_xtream: ^0.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.2.0
  dart_mappable_builder: ^4.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.9.5
  swagger_dart_code_generator: ^4.0.2

flutter:
  # TODO: Set to false once we have custom video controls
  uses-material-design: true
  generate: true